сетка на флексах основной страницы
htmlacademy-htmlcss/222997-nerds-29 pull request #13
Opened 2020-10-06 21:03 UTC by IgorChesalin

2020-10-07 04:38 UTC, mouxez requested changes

2020-10-07 04:38 UTC, mouxez commented on css/style.css
> +/* .products-list li:not(:first-child) {
ну это два селектора получается, так что преступления нет тут)

2020-10-07 04:38 UTC, mouxez commented on css/style.css
> +  width: 250px;
перенос надо делать с помощью ограничения ширины блока с текстом, так что норм

2020-10-07 04:38 UTC, mouxez commented on css/style.css
> +  width: 250px;
если есть особые случаи с переносом, то используй спец символы, например, неразрывный пробел

2020-10-07 04:38 UTC, mouxez commented on css/style.css
> +  width: 250px;
возможно, могут на защите вопросы быть к селектору li.products-item p
можно пока оставить так и если попросят исправить, то это можно достаточно быстро сделать

2020-10-07 04:38 UTC, mouxez commented on index.html
> +        <!-- можно ли тут использовать бр? или разбить текст на 2 строки -->
надо шириной блока сделать перенос текста

2020-10-07 04:38 UTC, mouxez commented on index.html
> +          <button class="products-item-button red-button border-clear" type="button">ЗАКАЗАТЬ</button>
как правило, текст в самом html указывают по правилам написания (Заказать), а потом уже в css доводят до необходимого вида
но это не обязательно править

2020-10-07 04:38 UTC, mouxez commented on index.html
> +            <span class="strong">146%</span>
так тоже ок
меньше проблем, чем с таблицами

2020-10-08 15:39 UTC, IgorChesalin commented on css/style.css
> +/* .products-list li:not(:first-child) {
убрал ли.

2020-10-08 15:40 UTC, IgorChesalin commented on css/style.css
> +  width: 250px;
поправил шириной блока

2020-10-08 15:44 UTC, IgorChesalin commented on index.html
> +        <!-- можно ли тут использовать бр? или разбить текст на 2 строки -->
никак не получается, с пробелами тоже

2020-10-08 15:44 UTC, IgorChesalin commented on index.html
> +          <button class="products-item-button red-button border-clear" type="button">ЗАКАЗАТЬ</button>
поправил, сделал апперкейс

2020-10-10 07:04 UTC, merged