Разметка внутренней страницы
htmlacademy-htmlcss/222997-nerds-29 pull request #7
Opened 2020-09-14 15:37 UTC by IgorChesalin

2020-09-14 16:09 UTC, mouxez requested changes

2020-09-14 16:09 UTC, mouxez commented on catalog.html
> +          <li><a href="index.html">Студия</a></li>
тайтл нужен у всех активных ссылок

2020-09-14 16:09 UTC, mouxez commented on catalog.html
> +          <img src="https://via.placeholder.com/150" alt="Логотип Нёрдс" />
смотри, лого и корзина это НЕ навигация, но находятся в хедере
это относится и к главной странице

2020-09-15 07:43 UTC, IgorChesalin commented on catalog.html
> +        <a href="#">Корзина</a>
# убрал

2020-09-15 07:46 UTC, IgorChesalin commented on catalog.html
> +          <li>по цене</li>
ок убрал список, сделал кнопки

2020-09-15 07:47 UTC, IgorChesalin commented on catalog.html
> +        <ul style="list-style-type: none">
убрал, хз зачем сделал, для красоты)

2020-09-15 07:53 UTC, IgorChesalin commented on catalog.html
> +            <img src="https://via.placeholder.com/150x100" alt="Превью сайта" />
есть

2020-09-15 07:55 UTC, IgorChesalin commented on catalog.html
> +          <img src="https://via.placeholder.com/150" alt="Логотип Нёрдс" />
вытащил из нава, на двух страницах

2020-09-15 07:58 UTC, IgorChesalin commented on catalog.html
> +          <li><a href="index.html">Студия</a></li>
вроде везде поправил

2020-09-15 12:45 UTC, merged