Стилизация каталога
htmlacademy-htmlcss/222997-nerds-29 pull request #9
Opened 2020-09-19 14:29 UTC by IgorChesalin

2020-09-20 06:35 UTC, mouxez requested changes

2020-09-20 06:35 UTC, mouxez commented on index.html
> +<html class="page" lang="ru">
для чего нужен класс тэгу html?
как правило, этот тэг не стилизуют.
плюс я не нашёл стили для class="page". удали все классы, для которых нет стилей в файле style.css

2020-09-20 06:35 UTC, mouxez commented on index.html
>  <body class="page-body">
не нашёл стили для class="page-body"

2020-09-20 06:35 UTC, mouxez commented on catalog.html
> +        <a href="" class="main-basket">Корзина</a>
тут нужен title

2020-09-20 06:35 UTC, mouxez commented on catalog.html
> +          <span class="filter-header-button">по цене</span>
для чего нужен дополнительный спан в кнопке?

2020-09-20 06:35 UTC, mouxez commented on catalog.html
> +        <button class="filter-button" type="button">Показать</button>
а тут не спана в кнопке и это хорошо

2020-09-20 06:35 UTC, mouxez commented on css/style.css
>    color: #ffffff;
цвета везде должны быть через var

2020-09-20 06:41 UTC, mouxez requested changes

2020-09-20 06:41 UTC, mouxez commented on css/style.css
>    --background: #888888;
фон не такого цвета
тут ты используешь цвет фона самой фигмы, а нужен цвет фона макета

2020-09-20 06:41 UTC, mouxez commented on css/style.css
>    --background: #888888;
![Screenshot 2020-09-20 at 09 39 30](https://user-images.githubusercontent.com/48134013/93705371-582e1c00-fb25-11ea-9c7d-413f2e54b563.png)
1 - фон фигмы
2 - фон хедера
3 - фон страницы сайта

2020-09-21 07:31 UTC, IgorChesalin commented on index.html
> +<html class="page" lang="ru">
Делал как в демке/лекции, думал пригодится. Поправил )

2020-09-21 07:38 UTC, IgorChesalin commented on catalog.html
> +        <a href="" class="main-basket">Корзина</a>
поправил

2020-09-21 07:40 UTC, IgorChesalin commented on catalog.html
> +          <span class="filter-header-button">по цене</span>
ставил спаны, чтобы их стилизовать, а не кнопку, убираю в кнопку с "обнулением" стилей

2020-09-21 07:44 UTC, IgorChesalin commented on css/style.css
>    color: #ffffff;
поправил

2020-09-21 07:48 UTC, IgorChesalin commented on css/style.css
>    --background: #888888;
поправил

2020-09-21 16:08 UTC, mouxez approved these changes

2020-09-21 16:08 UTC, merged